function [fitresult, gof] = createFit(projectsafe, projectlow, projecthigh)
%CREATEFIT(PC1,PC2,PC3)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : PC1
%      Y Input : PC2
%      Z Output: PC3
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 31-Dec-2020 18:34:46


%% Fit: 'untitled fit 1'.
[xData_safe, yData_safe, zData_safe] = prepareSurfaceData( projectedsafe(:,1), projectedsafe(:,2), projectedsafe(:,3) );

% Set up fittype and options.
ft = fittype( '-1/C*(A*x + B*y + D)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.913375856139019 0.63235924622541 0.0975404049994095 0.278498218867048];

% Fit model to data.
[fitresult_safe, gof] = fit( [xData_safe, yData_safe], zData_safe, ft, opts );


[xData_low, yData_low, zData_low] = prepareSurfaceData( projectedlow(:,1), projectedlow(:,2), projectedlow(:,3) );

% Set up fittype and options.
ft = fittype( '-1/C*(A*x + B*y + D)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.157613081677548 0.970592781760616 0.957166948242946 0.485375648722841];

% Fit model to data.
[fitresult_low, gof] = fit( [xData_low, yData_low], zData_low, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h_safe = plot( fitresult_safe );
hold on
h_low = plot( fitresult_low );
legend( h_low, 'untitled fit 1', 'PC3 vs. PC1, PC2', 'Location', 'NorthEast' );
% Label axes
xlabel PC1
ylabel PC2
zlabel PC3
grid on
% view( 53.8, 42.3 );


%% Fit: 'untitled fit 1'.
[xData_high, yData_high, zData_high] = prepareSurfaceData( projectedhigh(:,1), projectedhigh(:,2), projectedhigh(:,3) );

% Set up fittype and options.
ft = fittype( '-1/C*(A*x + B*y + D)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.915735525189067 0.792207329559554 0.959492426392903 0.655740699156587];

% Fit model to data.
[fitresult_high, gof] = fit( [xData_high, yData_high], zData_high, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h_safe = plot( fitresult_safe );
hold on
h_high = plot( fitresult_high );
legend( h_high, 'untitled fit 1', 'PC3 vs. PC1, PC2', 'Location', 'NorthEast' );
% Label axes
xlabel PC1
ylabel PC2
zlabel PC3
grid on
% view( 50.6, 14.7 );
